version: '3.9'
services:
    db:
        image: postgres:16-alpine
        container_name: comments_db
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - ./data/db:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U app -d comments']
            interval: 5s
            timeout: 5s
            retries: 10

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_CONFIG_SERVER_MODE=False
        ports:
            - '5050:80'
        volumes:
            - ./data/pgadmin:/var/lib/pgadmin
        restart: unless-stopped
